version: '3.9'

services:
  web:
    build: .
    cpus: 0.5
    mem_limit: 128M
    env_file:
      - .env.dev
    ports:
      - "5000"
    secrets:
      - postgres_password
    environment:
      - FLASK_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_SERVICE=db
      - POSTGRES_DB=mydb
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - flask-app-storage:/var/log
    networks:
      - infra-network

  proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - infra-network

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    secrets:
      - postgres_password
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    networks:
      - infra-network

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - redis-storage:/data
    networks:
      - infra-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - infra-network

volumes:
  postgres-storage:
  flask-app-storage:
  redis-storage:

networks:
  infra-network:
    driver: bridge

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt # This file must be in the .gitignore (I left it out for demo purposes)
